### PR TITLE
Reg filesystem

### PR DESCRIPTION
**Pull request by regkrock**
Removal of File references from FileSystemGs. The File class is still present but is in a deprecated state.

### CODE REVIEW

**Comment by regkrock** [comment]
I was wanting your feedback first.

Guille was definitely interested in my old proposal.

Regards,

Reg

**Comment by dalehenrich** [comment]
I went ahead and completed the merge, **before** running [the tests](https://github.com/GemTalk/Rowan/blob/smalltalkci_port/platforms/gemstone/topaz/rowanTestSuite.gs). 

The first thing that happened is that the pre-test-load audit failed:
```
==============Auditing project Rowan
  -- Auditing package Rowan-Cypress-Core
  -- Auditing package Rowan-Tools-Core
  -- Auditing package Rowan-Configurations
  -- Auditing package Rowan-GemStone-Loader
  -- Auditing package Rowan-Services-Extensions
  -- Auditing package GemStone-Interactions-Core
  -- Auditing package Rowan-Cypress-Definitions
  -- Auditing package Rowan-Url-3215
  -- Auditing package Rowan-Tools-Extensions
  -- Auditing package Rowan-Core-Definitions-Extensions
  -- Auditing package GemStone-Interactions-Kernel
  -- Auditing package Rowan-Cypress-Kernel
  -- Auditing package Rowan-Kernel
  -- Auditing package Rowan-GemStone-Loader-Extensions
  -- Auditing package Rowan-Definitions
  -- Auditing package Rowan-GemStone-Definitions
  -- Auditing package Rowan-GemStone-Core
  -- Auditing package Rowan-Services-Tests
  -- Auditing package Rowan-GemStone-Kernel
  -- Auditing package Rowan-Url-Extensions
  -- Auditing package Rowan-GemStone-Specifications
  -- Auditing package Rowan-Services-Core
  -- Auditing package Rowan-Tests
  -- Auditing package Rowan-Specifications
  -- Auditing package Rowan-GemStone-3215
  -- Auditing package Rowan-Core
  -- Auditing package Rowan-JadeServer
  -- Auditing package Rowan-Url-Core
  -- Auditing package Rowan-Tools-Kernel
==============Auditing project STON
  -- Auditing package STON-Core
  -- Auditing package STON-GemStoneBase
  -- Auditing package STON-GemStoneCommon
==============Auditing project Cypress
  -- Auditing package Cypress-Network-Url
  -- Auditing package Cypress-PackageManagement
  -- Auditing package Cypress-Definitions
Missing loaded instance method.   CypressSnapshot >> snapshot
Missing loaded instance method.   CypressSnapshot >> snapshot
Missing loaded instance method.   CypressMethodDefinition >> isExtensionMethod
Missing loaded instance method.   CypressMethodDefinition >> fullClassName
Missing loaded instance method.   CypressMethodDefinition >> sortKey
Missing loaded instance method.   CypressMethodDefinition >> isMethodDefinition
Missing loaded instance method.   CypressMethodDefinition >> isExtensionMethod
Missing loaded instance method.   CypressMethodDefinition >> fullClassName
Missing loaded instance method.   CypressMethodDefinition >> sortKey
Missing loaded instance method.   CypressMethodDefinition >> isMethodDefinition
  -- Auditing package Cypress-Environmental-Tools
  -- Auditing package Cypress-GemStoneFileServer
  -- Auditing package Cypress-Comparison
  -- Auditing package Cypress-Structure
  -- Auditing package Cypress-MesssageDigest

```
These audit errors imply that the "missing methods" were moved to a different package without rewriting the Cypress packages ... not a big problem, since it should be easy to resolve this.

When I commented out the audit here are the test failures:
```
Rowan STON Cypress Tonel FileSystemGs tests for GemStone '3.2.15'
1442 run, 1395 passed, 12 failed, 35 errors
  errors
	NumberParserTest>>#testFloatGradualUnderflow
	NumberParserTest>>#testFloatmin
	RwBrowserToolApiTest>>#testIssue471_1
	RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
	RwBrowserToolApiTest>>#testNewClassVersion_session_method_change_extension_method_source
	RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
	RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
	RwProjectFiletreeReaderWriterTest>>#testWriterReader_A
	RwProjectTonelReaderWriterTest>>#testWriterReader_A
	StdioStreamTest>>#testAtEnd
	StdioStreamTest>>#testChangePosition
	StdioStreamTest>>#testContents
	StdioStreamTest>>#testPeek
	StdioStreamTest>>#testPosition
	StdioStreamTest>>#testSize
	StdioStreamTest>>#testUpToEnd
	ZnCharacterEncoderTests>>#testByteEncoderFromUrl
	ZnFileUrlTests>>#testRetrieveContents
	ZnFileUrlTests>>#testSpaces
	ZnFileUrlTests>>#testWindowsDriveNamesInFileUrl
	ZnResourceMetaUtilsTests>>#testQueryParsing
	ZnUrlTests>>#testConvenienceMethods
	ZnUrlTests>>#testInContextOf
	ZnUrlTests>>#testLocalHost
	ZnUrlTests>>#testMailto
	ZnUrlTests>>#testParsePathOnly
	ZnUrlTests>>#testPathRemoval
	ZnUrlTests>>#testPathSegments
	ZnUrlTests>>#testPlus
	ZnUrlTests>>#testPlusHandling
	ZnUrlTests>>#testQueryAccessing
	ZnUrlTests>>#testQueryEncodingExtended
	ZnUrlTests>>#testQueryManipulation
	ZnUrlTests>>#testSchemeInQuery
	ZnUrlTests>>#testWindowsFileUrl
  failures
	ClientFileSystemTest>>#testDefaultWorkingDirectory
	RowanMethodServiceTest>>#test_noStepPoints
	RowanMethodServiceTest>>#test_stepPoint1
	RowanMethodServiceTest>>#test_stepPoint2
	RowanMethodServiceTest>>#test_stepPoint3
	RwLoadingTest>>#testPoolDictionaryChanges
	RwSemanticVersionNumberTestCase>>#testOfficialInvalidSemanticVersions
	RwSymbolDictionaryTest>>#testClassVersioningPatch
	ZnCharacterEncoderTests>>#testAllByteEncoderDomains
	ZnCharacterEncoderTests>>#testReadIntoStartingAtCountFromStreamWide
	ZnCharacterEncoderTests>>#testUTF8ByteOrderMark
	ZnCharacterEncoderTests>>#testUTF8ReadFaultyInput
```
For comparison, here are the expected test results from a run without the latest FileSystem changes:
```
    Rowan STON Cypress Tonel FileSystemGs tests for GemStone '3.2.15'
    1137 run, 1119 passed, 7 failed, 11 errors
      errors
        FileHandleTest>>#testTruncate
        FileReferenceTest>>#testUpToAll
        RwBrowserToolApiTest>>#testIssue471_1
        RwBrowserToolApiTest>>#testMoveGlobalExtensionSessionMethods
        RwBrowserToolApiTest>>#testNewClassVersion_session_method_change_extension_method_source
        RwHybridBrowserToolTest>>#testHybridMoveMethodFromSessionMethodsIntoSessionMethods
        RwHybridBrowserToolTest>>#testHybridMoveMethodIntoSessionMethods
        RwProjectFiletreeReaderWriterTest>>#testWriterReader_A
        RwProjectTonelReaderWriterTest>>#testWriterReader_A
        RwRowanSample2Test>>#testNoMigration_gitolite
        ZnCharacterEncoderTests>>#testUTF8Back
      failures
        RowanMethodServiceTest>>#test_noStepPoints
        RowanMethodServiceTest>>#test_stepPoint1
        RowanMethodServiceTest>>#test_stepPoint2
        RowanMethodServiceTest>>#test_stepPoint3
        RwLoadingTest>>#testPoolDictionaryChanges
        RwSemanticVersionNumberTestCase>>#testOfficialInvalidSemanticVersions
        RwSymbolDictionaryTest>>#testClassVersioningPatch
```
The good news is that it doesn't appear that the new filesystem code has affected the operation of Rowan itself. the "bad news" is that the unexpected failing tests are part of the FileSystem test suite ... it is possible that some of these tests are no longer applicable , so it would be useful to find out which tests should be expected to pass and remove the rest of the tests/code ... for example I am curious if the ZN stream code is still expected to be used or have they been replaced?

**Comment by regkrock** [comment]
Hi Dale,

I am half way to Canada. I will look at in more detail this evening.
Regards,

Reg

Sent from my iPhone

**Comment by regkrock** [comment]
Hi Dale,

So I need to have you do the following:

1) Do not load the following packages:

	These were packages I copied from Pharo to experiment with ZnUrl.

		Zinc-Resource-Meta-Core
		Zinc-Resource-Meta-FileSystem
		Zinc-Resource-Meta-Tests

	The code fails mainly on Unicode to String comparisons. But this is outside of the scope. This will eliminate the following failures:

		ZnFileUrlTests debug: #testRetrieveContents.
		ZnFileUrlTests debug: #testSpaces.
		ZnFileUrlTests debug: #testWindowsDriveNamesInFileUrl.
		ZnResourceMetaUtilsTests debug: #testQueryParsing.
		ZnUrlTests debug: #testConvenienceMethods.
		ZnUrlTests debug: #testInContextOf.
		ZnUrlTests debug: #testLocalHost.
		ZnUrlTests debug: #testMailto.
		ZnUrlTests debug: #testParsePathOnly.
		ZnUrlTests debug: #testPathRemoval.
		ZnUrlTests debug: #testPathSegments.
		ZnUrlTests debug: #testPlus.
		ZnUrlTests debug: #testPlusHandling.
		ZnUrlTests debug: #testQueryAccessing.
		ZnUrlTests debug: #testQueryEncodingExtended.
		ZnUrlTests debug: #testQueryManipulation.
		ZnUrlTests debug: #testSchemeInQuery.
		ZnUrlTests debug: #testWindowsFileUrl.

2) The ZnCharacterEncoderTests errors:
	Ignore these errors. In fact you can comment out the tests. These will only pass when Unicode8 is functioning.

	"Failures"
	ZnCharacterEncoderTests debug: #testAllByteEncoderDomains.
	ZnCharacterEncoderTests debug: #testReadIntoStartingAtCountFromStreamWide.
	ZnCharacterEncoderTests debug: #testUTF8ByteOrderMark.
	ZnCharacterEncoderTests debug: #testUTF8ReadFaultyInput.

	"Errors"
	ZnCharacterEncoderTests debug: #testByteEncoderFromUrl.

3) #testFileNames - This is a known failure on opening a file with umlauts in the name. 

	One time you mentioned that you thought this problem is resolved in later editions of GemStone.
	
	"Errors"
		DiskFileSystemTest debug: #testFileNames.

4) As part of working on ZnUrl, I ported the NumberParser from Pharo to GemStone.
    These two tests fail because I did not know to handle positive and negative infinity since the two implementations are different.

    The NumberParser test failures can be  be ignored for now.

	"Errors"
		NumberParserTest debug: #testFloatGradualUnderflow.
		NumberParserTest debug: #testFloatmin.


5) ClientFileSystemTest>>#testDefaultWorkingDirectory

	This test assumes there is a client system. And it makes a guess at the Unix side. So it is failing because there is no client OR my guess at the UNIX test conditions is wrong.

6) StdioStreamTests failures
	Ignore them and I will see what went wrong. There is a Test Resource associated with these tests and I wonder if that may be part of the problem.

> On 10 Mar2019, at 12:39 PM, Dale Henrichs <notifications@github.com> wrote:
> 
> I went ahead and completed the merge, before running the tests <https://github.com/GemTalk/Rowan/blob/smalltalkci_port/platforms/gemstone/topaz/rowanTestSuite.gs>.
> 
> The first thing that happened is that the pre-test-load audit failed:
> 
> ==============Auditing project Rowan
>   -- Auditing package Rowan-Cypress-Core
>   -- Auditing package Rowan-Tools-Core
>   -- Auditing package Rowan-Configurations
>   -- Auditing package Rowan-GemStone-Loader
>   -- Auditing package Rowan-Services-Extensions
>   -- Auditing package GemStone-Interactions-Core
>   -- Auditing package Rowan-Cypress-Definitions
>   -- Auditing package Rowan-Url-3215
>   -- Auditing package Rowan-Tools-Extensions
>   -- Auditing package Rowan-Core-Definitions-Extensions
>   -- Auditing package GemStone-Interactions-Kernel
>   -- Auditing package Rowan-Cypress-Kernel
>   -- Auditing package Rowan-Kernel
>   -- Auditing package Rowan-GemStone-Loader-Extensions
>   -- Auditing package Rowan-Definitions
>   -- Auditing package Rowan-GemStone-Definitions
>   -- Auditing package Rowan-GemStone-Core
>   -- Auditing package Rowan-Services-Tests
>   -- Auditing package Rowan-GemStone-Kernel
>   -- Auditing package Rowan-Url-Extensions
>   -- Auditing package Rowan-GemStone-Specifications
>   -- Auditing package Rowan-Services-Core
>   -- Auditing package Rowan-Tests
>   -- Auditing package Rowan-Specifications
>   -- Auditing package Rowan-GemStone-3215
>   -- Auditing package Rowan-Core
>   -- Auditing package Rowan-JadeServer
>   -- Auditing package Rowan-Url-Core
>   -- Auditing package Rowan-Tools-Kernel
> ==============Auditing project STON
>   -- Auditing package STON-Core
>   -- Auditing package STON-GemStoneBase
>   -- Auditing package STON-GemStoneCommon
> ==============Auditing project Cypress
>   -- Auditing package Cypress-Network-Url
>   -- Auditing package Cypress-PackageManagement
>   -- Auditing package Cypress-Definitions
> Missing loaded instance method.   CypressSnapshot >> snapshot
> Missing loaded instance method.   CypressSnapshot >> snapshot
> Missing loaded instance method.   CypressMethodDefinition >> isExtensionMethod
> Missing loaded instance method.   CypressMethodDefinition >> fullClassName
> Missing loaded instance method.   CypressMethodDefinition >> sortKey
> Missing loaded instance method.   CypressMethodDefinition >> isMethodDefinition
> Missing loaded instance method.   CypressMethodDefinition >> isExtensionMethod
> Missing loaded instance method.   CypressMethodDefinition >> fullClassName
> Missing loaded instance method.   CypressMethodDefinition >> sortKey
> Missing loaded instance method.   CypressMethodDefinition >> isMethodDefinition
>   -- Auditing package Cypress-Environmental-Tools
>   -- Auditing package Cypress-GemStoneFileServer
>   -- Auditing package Cypress-Comparison
>   -- Auditing package Cypress-Structure
>   -- Auditing package Cypress-MesssageDigest
> 
> These audit errors imply that the "missing methods" were moved to a different package without rewriting the Cypress packages ... not a big problem, since it should be easy to resolve this.
> 
> When I commented out the audit here are the test failures:
> 
> Rowan STON Cypress Tonel FileSystemGs tests for GemStone '3.2.15'
> 1442 run, 1395 passed, 12 failed, 35 errors
>   errors
> 	NumberParserTest>>#testFloatGradualUnderflow
ignore - see above
> 	NumberParserTest>>#testFloatmin
ignore - see above

**Comment by dalehenrich** [comment]
@regkrock, I've removed the Zinc-Meta-* packages and fixed the audit errors ... I assume that NumberParser and tests can be removed, since it doesn't appear to be being used now?

I think we're good to go now ... so let me (and @martinmcclure) know when you are ready to turn the work over t o us...

**Comment by regkrock** [comment]
The NumberParser and NumberParserTest are used by Zinc-Meta...  if you can keep them together that would be great.

Reg

**Comment by regkrock** [comment]
I just removed the packages from the git checkin so they will exist in 
history ... are you planning on doing any more work? If so you can 
remove the classes in Jadeite and they will be removed when you commit 
from Jadeite ...

Dale

**Pull request merged**
