### PR TITLE
Added ability to audit from another user. User must have visibility t…

### LINKED ISSUE #471: RwGsPatchSet_254>>updateClassProperties performed when no explicit property changes made in SHARED project definition
This is the stack from the original test case I plan to add a test case for this issue:
```
a UserDefinedError occurred (error 2318), reason:halt, Superclass not found: 'Issue470Class2'
UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsPatchSet_254 (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsPatchSet_254) >> superclassNamed: @4 line 10
SymbolDictionary >> at:ifAbsent: @12 line 18
[] in  ExecBlock0 (RwGsPatchSet_254) >> superclassNamed: @2 line 9
Dictionary >> at:ifAbsent: @7 line 10
RwGsPatchSet_254 >> superclassNamed: @4 line 6
RwGsClassPropertiesSymDictPatch (RwGsClassPatch) >> privateCreateClassFor: @3 line 4
RwGsClassPropertiesSymDictPatch (RwGsClassPatch) >> createClassFor: @2 line 4
RwGsClassPropertiesSymDictPatch >> installPropertiesPatchFor:registry: @8 line 13
RwGsClassPropertiesSymDictPatch >> installPropertiesPatchFor: @3 line 3
[] in  ExecBlock1 (RwGsPatchSet_254) >> updateClassProperties @5 line 11
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSet_254 >> updateClassProperties @6 line 9
RwGsPatchSet_254 >> apply @24 line 26
RwGsTestImage class (RwGsImage class) >> applyModification_254:visitorClass:instanceMigrator: @10 line 9
RwGsTestImage class (RwGsImage class) >> applyModification_254:instanceMigrator: @8 line 12
RwPrjLoadTool >> _loadProjectSetDefinition_254:instanceMigrator: @17 line 18
[] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @3 line 7
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
RwBrowserToolApiTest >> testXXX @68 line 110
RwBrowserToolApiTest (TestCase) >> performTest @3 line 2
[] in  ExecBlock0 (TestCase) >> runCase @3 line 5
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwBrowserToolApiTest (TestCase) >> runCase @4 line 6
[] in  ExecBlock0 (TestCase) >> debug @4 line 2
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwBrowserToolApiTest (TestCase) >> debug @2 line 3
RwBrowserToolApiTest class (TestCase class) >> debug: @3 line 3
[] in  ExecBlock1 (RowanAnsweringService) >> runMethodTests: @9 line 7
Array (Collection) >> do: @5 line 10
RowanAnsweringService >> runMethodTests: @2 line 4
RowanAnsweringService (RowanService) >> servicePerform:withArguments: @2 line 2
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @10 line 12
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```
The test case involves removing a class from a package in which there is another class (not removed) that is a subclass of the removed class ... 

The interesting twist is that the class removal is done in the original definition structure that was fed to the load command ... if a fresh copy of the definition structure is used, the error does not occur ... the implication is that thesource definition structure is modified during the load and I am not completely convinced that that is kosher ... I'll add two tests (one passing and one failing) and expect to address this as part of v2 work.

### PR DESCRIPTION
**Pull request by alexkogan**
Fixes #471. Added audit packages for another users requires RowanTools and RowanKernel dictionaries as well as RwProjectSymbolDictionaryRegistry

### CODE REVIEW

**Comment by alexkogan** [comment]
updated to go to candidateV1.2

**Comment by alexkogan** [comment]
Sure. I swear I merged

**Comment by alexkogan** [comment]
I picked up those changes when I was verifying your fix.

**Comment by dalehenrich** [comment]
I'm not trying to give you a hard time ... I'm surprised to see those changes show up as changes in your checking and I'm trying to figure out why that is happening ... at first I though I had made a mistake and not actually shipped the changes:)

If you look at the (network graph](https://github.com/GemTalk/Rowan/network), it looks like [this](https://github.com/GemTalk/Rowan/commit/f23e1c3e87eb4e43880656f1b5ed417164b120db) was the last commit you merged into the alex branch on the 20th of November.

I didn't fix issue #419 until the 21st of November with [this](https://github.com/GemTalk/Rowan/commit/095dfdbf76d8e920a83644d2a295126554189ca8) commit ...

According to [blame](https://github.com/GemTalk/Rowan/blame/b678a01b89b4f91c939fa780a2856f30258530ab/rowan/src/Rowan-GemStone-Loader/RwGsSymbolDictionaryRegistry_Implementation.class.st):
image
The change `self _clearLookupCachesFor: behavior env: 0` was added with your commit 5 hours ago ...

So, if you could merge masterV1.2 (make sure to do a `git pull origin` after the `git checkout masterV1.2` ... this is my guess as to what happened ... you merge masterV1.2, but it was an older version) into your alex branch... and the do a `git push origin alex` the pull request will be updated ... oh and pleas make the other change I requested in the review... then we'll be good to go ...

**Comment by alexkogan** [comment]
I picked up those changes on 21st when you asked me to verify.
I hope I got it right this time. could you verify my new pull request.

**Comment by dalehenrich** [comment]
Everything looks fine ... when you merged masterv1.2 those changes went away and all that was left was your changes for issue #427

**Pull request merged**
